### PR TITLE
Draft: Utilities module

### PR DESCRIPTION
**Pull request by dtgaebe**
## Description
With this PR a `utilities.py` module is added to the code. In `utilities.py` there are several functions commonly used in WEC analysis, but that are not required for the optimization problem itself.

## Type of PR
- [ ] Bug fix
- [x] New feature
- [ ] Documentation
- [ ] Other: (specify)

## Checklist for PR
- [x] Authors read the [contribution guidelines](https://github.com/sandialabs/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on *your* fork, to the [main branch in WecOptTool](https://github.com/sandialabs/WecOptTool).
- [x] The authors have given the admins edit access
- [x] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [x] Modified the documentation if applicable
- [x] Modified or added a new test
- [x] All tests pass
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Additional details
Utility functions so far include:

- Calculating the natural frequency for DoFs with natural restoring force based on the `hydrodynamic_impedance` (intrinsic impedance
- Plotting the BEM results based on all available DoFs in `bem_data`
- Plotting the Bode graph of all the DoFs in the `hydrodynamic_impedance`

### CODE REVIEW

**Comment by dtgaebe** [comment]
TODO:
Update the tutorials and use the new utility functions where appropriate

**Comment by dtgaebe** [comment]
Other utils funcitons
- [ ] function for reading or running bem - read if freqs and mesh is identical, else run bem

**Comment by cmichelenstrofer** [comment]
Other functions to consider for the `utilities` module in future PR:

- Thévenin equivalent system: 
    - linear solution
    - natural frequency of full Thévenin equivalent system
- Plots: Smith plots?

**Comment by cmichelenstrofer** [comment]
The code used to have several other functions that were eliminated, but that makes sense to bring back into this `utilities` submodule. E.g. #89: power limit, optimal velocity (linear theory),

**Comment by dtgaebe** [comment]
The current version of this PR has 4 new utility functions and tests for them

1. plot_hydrodynamic_coefficients
2. plot_bode_impedance
3. calculate_power_flows
4. plot_power_flow

**Comment by michaelcdevin** [comment]
@dtgaebe: just to confirm, can we close this PR without merging since #343 has now been merged in its place?

**Comment by dtgaebe** [comment]
@michaelcdevin , Yes. I'll close it

**Pull request closed without merging**
