### PR TITLE
consistent use xr.DataArray and xr.Dataset arguments

### LINKED ISSUE #183: `exc_coeff` needs to be an `xarray.Dataset`
```
/opt/anaconda3/lib/python3.9/site-packages/wecopttool/core.py in wave_excitation(exc_coeff, waves)
   2119     """
   2120     omega_w = waves['omega'].values
-> 2121     omega_e = exc_coeff['omega'].values
   2122     dir_w = waves['wave_direction'].values
   2123     dir_e = exc_coeff['wave_direction'].values

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

### PR DESCRIPTION
**Pull request by jtgrasb**
## Description
This pull request makes the `exc_coeff` to be consistently a `DataArray` throughout the multiple functions that use it. I also briefly checked some of the other docstrings to confirm inputs and outputs are accurately recorded.

Closes #183

## Type of PR
- [X] Bug fix
- [ ] New feature
- [X] Documentation
- [ ] Other: (specify)

## Checklist for PR
- [X] Authors read the [contribution guidelines](https://github.com/sandialabs/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [X] The pull request is from an issue branch (not main) on *your* fork, to the [main branch in WecOptTool](https://github.com/sandialabs/WecOptTool).
- [X] The authors have given the admins edit access
- [X] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [X] Modified the documentation if applicable
- [ ] Modified or added a new test
- [ ] All tests pass
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Additional details
This is in response to issue #183. @akeow I don't know what caused the initial issue so please let me know whether this solves the issue.

### CODE REVIEW

**Comment by jtgrasb** [comment]
Solve docstring should be fixed now @cmichelenstrofer

**Comment by ryancoe** [comment]
@jtgrasb - I think this may also need to be updated for the static methods for creating `wec` objects. For example

https://github.com/sandialabs/WecOptTool/blob/6c9b8524d80c1a4469d12b7d1a0b453089435458/wecopttool/core.py#L511-L561

We should get consistent with this, or (ideally) program in a way that is agnostic to whether the users passes an `xr.dataarray` or `np.ndarray`

**Comment by jtgrasb** [comment]
@ryancoe I changed the title of this PR as it was backwards previously. The PR makes exc_coeff an ArrayLike input wherever it is used. The ArrayLike specification is agnostic to whether the users passes an `xr.dataarray` or `np.ndarray`. I think what you're suggesting is to be consistent for other variables such as the hydrostatic_stiffness? If so, I can amend this to make sure that and other variables are all agnostic to array input type.

**Comment by ryancoe** [comment]
Per discussion today: we like indexing by name, so require the arguments to be `xr.DataArrays`, etc. After that, merge.

**Pull request merged**
